### ISSUE TITLE
resuming a save state sends an A button press.

### ISSUE THREAD

**Issue by thedicemaster** [PocketSprite/8bkc-gnuboy#3]
this is a minor inconvenience, but can cause some issues in some games.
if you resume a game from a save state the game will immediately respond to an A button press once loading completes.

in platformers with an "overworld" like donkey kong land and super mario land 2 this means a state saved on the overworld will immediately start the highlighted stage once the game is resumed.
and when a state is saved on an in-game save selection screen it will immediately load the highlighted in-game save.
other games might have even more disastrous results depending on the in-game situation and the way the A button is used.

**Comment by Spritetm** [comment]
Gotcha, I'll see if I can add a routine that waits for all keys to be released when I have some time.

**Comment by thedicemaster** [comment]
this issue no longer occurs after updating gnuboy and chooser with the test releases from reddit.
